name: Colab CI/CD Pipeline

on: [push]

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Adjust as necessary
      - name: Install Dependencies
        run: |
          pip install notebook ipykernel papermill yfinance numpy dask pyspark seaborn matplotlib scipy pandas
      - name: Execute Notebook
        run: papermill DATS-6501-Capstone.ipynb Output_Notebook.ipynb
