name: Colab CI/CD Pipeline

on:
  push:
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Runs every day at 05:00 UTC
    - cron:  '0 9 * * *'

jobs:
  run-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x' # Adjust as necessary
      - name: Install Dependencies
        run: |
          pip install notebook ipykernel papermill yfinance numpy dask pyspark seaborn matplotlib scipy pandas
      - name: Execute Notebook
        run: papermill Copy_of_DATS_6501_Capstone.ipynb Output_Notebook.ipynb
